---
- name: Création de l'utilisateur labuser
  hosts: all
  tasks:
    - name: Vérifier l'existence du groupe devops
      group:
        name: devops
        gid: 1500
      register: group_result
      ignore_errors: yes

    - name: Créer le groupe devops s'il n'existe pas
      group:
        name: devops
      when: group_result.failed

    - name: Créer l'utilisateur labuser
      user:
        name: labuser
        uid: 1999
        comment: "Utilisateur Lab"
        groups: devops
        password: "{{ 'labuser001' | password_hash('sha512', 'mysecretsalt') }}"
