- name: Exercice 7 - Redémarrage Apache
  hosts: web_servers
  tasks:
    - name: Installation Apache
      apt:
        name: apache2
        state: latest
      become: yes
    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted
      register: apache_restat_output
      ignore_errors: true
      become: yes
    - name: affiche le retour de la tache 2
      debug:
        msg: '{{ apache_restat_output }}'
    - name: Dire si la tâche a échouée
      debug:
        msg: "La tâche de redémarrage a échoué"
      when:
        - apache_restat_output.failed == true
