---
- name: Exercice 8 - Installation MySQL
  hosts: db_servers
  tasks:
    - name: Installer MySQL Server
      apt:
        name: mysql-server
        state: present
        update_cache: true
    - name: Copier le fichier de configuration MySQL
      copy:
        src: /tp/my.cnf
        dest: /etc/mysql/my.cnf
    - name: redémarrer mysql
      service:
        name: mysql
        state: restarted