---
- name: Exercice 9 - Déploiement de configuration
  hosts: web_servers
  tasks:
    - name: créer le répertoire /etc/app
      file:
        path: /etc/app
        state: directory
    - name: Copier le fichier de configuration à partir d'un modèle
      template:
        src: /tp/template
        dest: /etc/app/app.conf
